name: CI


on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
   style:
     runs-on: ubuntu-20.04
     container:
       image: dcluo28/dibasis:latest
     name: Repo Test

     steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Checkout hippylib
          run: git clone https://github.com/hippylib/hippylib.git
        - name: Check directory 
          run: ls 
        - name: Check user
          run: whoami 
        - name: Run unit tests 
          run: source .github/workflows/run_tests.sh
            # - name: Activate conda 
          # run: conda init && source ~/.bashrc && conda activate dibasis  
            # - name: Check conda 
          # run: conda info 
